// Auto-generated by sync.cjs
// DO NOT EDIT THIS FILE MANUALLY
export const portfolioData = {
  "5am in munich": [
    {
      "name": "5am in munich mid quality.mp4",
      "type": "Video",
      "size": "915 MB",
      "date": "Jan 13, 2026",
      "src": "5am%20in%20munich/5am%20in%20munich%20mid%20quality_web.mp4?v=1774994921230",
      "isVideo": true
    },
    {
      "name": "20250921-_DSC4935.jpg",
      "type": "Image",
      "size": "2.2 MB",
      "date": "Jan 14, 2026",
      "src": "5am%20in%20munich/20250921-_DSC4935.jpg?v=1768350206870",
      "isVideo": false
    },
    {
      "name": "20250923-_DSC4997.jpg",
      "type": "Image",
      "size": "1.5 MB",
      "date": "Jan 14, 2026",
      "src": "5am%20in%20munich/20250923-_DSC4997.jpg?v=1768350206280",
      "isVideo": false
    },
    {
      "name": "20250923-_DSC4998.jpg",
      "type": "Image",
      "size": "2 MB",
      "date": "Jan 14, 2026",
      "src": "5am%20in%20munich/20250923-_DSC4998.jpg?v=1768350206110",
      "isVideo": false
    },
    {
      "name": "20250924-_DSC5008.jpg",
      "type": "Image",
      "size": "1.3 MB",
      "date": "Jan 14, 2026",
      "src": "5am%20in%20munich/20250924-_DSC5008.jpg?v=1768350206020",
      "isVideo": false
    }
  ],
  "LDN x UKG": [
    {
      "name": "london x ukg.mp4",
      "type": "Video",
      "size": "232.9 MB",
      "date": "Jan 11, 2026",
      "src": "LDN%20x%20UKG/london%20x%20ukg_web.mp4?v=1774946226520",
      "isVideo": true
    },
    {
      "name": "20251220-_DSC5252.jpg",
      "type": "Image",
      "size": "2 MB",
      "date": "Jan 14, 2026",
      "src": "LDN%20x%20UKG/20251220-_DSC5252.jpg?v=1768352002870",
      "isVideo": false
    },
    {
      "name": "20251222-_DSC5308.jpg",
      "type": "Image",
      "size": "1.6 MB",
      "date": "Jan 14, 2026",
      "src": "LDN%20x%20UKG/20251222-_DSC5308.jpg?v=1768352002440",
      "isVideo": false
    },
    {
      "name": "20251222-_DSC5309.jpg",
      "type": "Image",
      "size": "1.7 MB",
      "date": "Jan 14, 2026",
      "src": "LDN%20x%20UKG/20251222-_DSC5309.jpg?v=1768352002130",
      "isVideo": false
    },
    {
      "name": "20251222-_DSC5313.jpg",
      "type": "Image",
      "size": "1.8 MB",
      "date": "Jan 14, 2026",
      "src": "LDN%20x%20UKG/20251222-_DSC5313.jpg?v=1768352001870",
      "isVideo": false
    },
    {
      "name": "20251222-_DSC5325.jpg",
      "type": "Image",
      "size": "1.7 MB",
      "date": "Jan 14, 2026",
      "src": "LDN%20x%20UKG/20251222-_DSC5325.jpg?v=1768352001000",
      "isVideo": false
    },
    {
      "name": "20251222-_DSC5329.jpg",
      "type": "Image",
      "size": "1.8 MB",
      "date": "Jan 14, 2026",
      "src": "LDN%20x%20UKG/20251222-_DSC5329.jpg?v=1768352000690",
      "isVideo": false
    },
    {
      "name": "20251222-_DSC5334.jpg",
      "type": "Image",
      "size": "1.9 MB",
      "date": "Jan 14, 2026",
      "src": "LDN%20x%20UKG/20251222-_DSC5334.jpg?v=1768352000630",
      "isVideo": false
    }
  ],
  "Lunatic": [
    {
      "name": "lunatic.mp4",
      "type": "Video",
      "size": "120.8 MB",
      "date": "Feb 18, 2025",
      "src": "Lunatic/lunatic_web.mp4?v=1774990398960",
      "isVideo": true
    },
    {
      "name": "20250209-_DSC3184.jpg",
      "type": "Image",
      "size": "1 MB",
      "date": "Jan 14, 2026",
      "src": "Lunatic/20250209-_DSC3184.jpg?v=1768353938620",
      "isVideo": false
    },
    {
      "name": "20250209-_DSC3248.jpg",
      "type": "Image",
      "size": "1005.5 KB",
      "date": "Jan 14, 2026",
      "src": "Lunatic/20250209-_DSC3248.jpg?v=1768353928070",
      "isVideo": false
    },
    {
      "name": "20250210-_DSC3589.jpg",
      "type": "Image",
      "size": "1.8 MB",
      "date": "Jan 14, 2026",
      "src": "Lunatic/20250210-_DSC3589.jpg?v=1768353909020",
      "isVideo": false
    },
    {
      "name": "20250214-_DSC4087.jpg",
      "type": "Image",
      "size": "914.6 KB",
      "date": "Jan 14, 2026",
      "src": "Lunatic/20250214-_DSC4087.jpg?v=1768353862370",
      "isVideo": false
    },
    {
      "name": "20250214-_DSC4114.jpg",
      "type": "Image",
      "size": "1.2 MB",
      "date": "Jan 14, 2026",
      "src": "Lunatic/20250214-_DSC4114.jpg?v=1768353821030",
      "isVideo": false
    }
  ],
  "TOMIN INDEX.TXT": [
    {
      "name": "032C",
      "type": "Magazine",
      "size": "--",
      "date": "Apr 20, 2025",
      "src": "",
      "isVideo": false,
      "isMagazine": true
    },
    {
      "name": "Numéro Berlin",
      "type": "Magazine",
      "size": "--",
      "date": "May 4, 2026",
      "src": "",
      "isVideo": false,
      "isMagazine": true
    },
    {
      "name": "RUSSH",
      "type": "Magazine",
      "size": "--",
      "date": "Jan 10, 2025",
      "src": "",
      "isVideo": false,
      "isMagazine": true
    }
  ],
  "TOMIN INDEX.TXT/032C": [
    {
      "name": "1.png",
      "type": "Image",
      "size": "1.7 MB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/032C/1.png?v=1774706465980",
      "isVideo": false
    },
    {
      "name": "2.png",
      "type": "Image",
      "size": "632.6 KB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/032C/2.png?v=1774706465980",
      "isVideo": false
    },
    {
      "name": "3.png",
      "type": "Image",
      "size": "1.9 MB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/032C/3.png?v=1774706466000",
      "isVideo": false
    },
    {
      "name": "4.png",
      "type": "Image",
      "size": "2 MB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/032C/4.png?v=1774706466000",
      "isVideo": false
    },
    {
      "name": "5.png",
      "type": "Image",
      "size": "468.8 KB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/032C/5.png?v=1774706466000",
      "isVideo": false
    },
    {
      "name": "6.png",
      "type": "Image",
      "size": "887.9 KB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/032C/6.png?v=1774706466000",
      "isVideo": false
    },
    {
      "name": "7.mp4",
      "type": "Video",
      "size": "375.2 KB",
      "date": "Mar 30, 2026",
      "src": "TOMIN%20INDEX.TXT/032C/7.mp4?v=1774888647830",
      "isVideo": true
    },
    {
      "name": "7.png",
      "type": "Image",
      "size": "982.3 KB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/032C/7.png?v=1774706466000",
      "isVideo": false
    },
    {
      "name": "9.png",
      "type": "Image",
      "size": "1.7 MB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/032C/9.png?v=1774706466000",
      "isVideo": false
    },
    {
      "name": "10.png",
      "type": "Image",
      "size": "1.8 MB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/032C/10.png?v=1774706466000",
      "isVideo": false
    },
    {
      "name": "11.png",
      "type": "Image",
      "size": "1.1 MB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/032C/11.png?v=1774706466000",
      "isVideo": false
    },
    {
      "name": "12.png",
      "type": "Image",
      "size": "1.9 MB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/032C/12.png?v=1774706465970",
      "isVideo": false
    },
    {
      "name": "13.png",
      "type": "Image",
      "size": "2.2 MB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/032C/13.png?v=1774706465970",
      "isVideo": false
    },
    {
      "name": "14.mp4",
      "type": "Video",
      "size": "455.4 KB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/032C/14.mp4?v=1774706990690",
      "isVideo": true
    },
    {
      "name": "15.png",
      "type": "Image",
      "size": "777.1 KB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/032C/15.png?v=1774706465980",
      "isVideo": false
    },
    {
      "name": "16.png",
      "type": "Image",
      "size": "729.4 KB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/032C/16.png?v=1774706465980",
      "isVideo": false
    },
    {
      "name": "17.png",
      "type": "Image",
      "size": "836.6 KB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/032C/17.png?v=1774706465990",
      "isVideo": false
    },
    {
      "name": "18.png",
      "type": "Image",
      "size": "771.7 KB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/032C/18.png?v=1774706465990",
      "isVideo": false
    },
    {
      "name": "19.png",
      "type": "Image",
      "size": "938.5 KB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/032C/19.png?v=1774706465960",
      "isVideo": false
    },
    {
      "name": "20.png",
      "type": "Image",
      "size": "837.9 KB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/032C/20.png?v=1774706465960",
      "isVideo": false
    }
  ],
  "TOMIN INDEX.TXT/Numéro Berlin": [
    {
      "name": "1.png",
      "type": "Image",
      "size": "2.1 MB",
      "date": "May 3, 2026",
      "src": "TOMIN%20INDEX.TXT/Nume%CC%81ro%20Berlin/1.png?v=1777837540850",
      "isVideo": false
    },
    {
      "name": "2.png",
      "type": "Image",
      "size": "2 MB",
      "date": "May 3, 2026",
      "src": "TOMIN%20INDEX.TXT/Nume%CC%81ro%20Berlin/2.png?v=1777837540870",
      "isVideo": false
    },
    {
      "name": "3.png",
      "type": "Image",
      "size": "1.2 MB",
      "date": "May 4, 2026",
      "src": "TOMIN%20INDEX.TXT/Nume%CC%81ro%20Berlin/3.png?v=1777873598750",
      "isVideo": false
    },
    {
      "name": "4.png",
      "type": "Image",
      "size": "335.4 KB",
      "date": "May 4, 2026",
      "src": "TOMIN%20INDEX.TXT/Nume%CC%81ro%20Berlin/4.png?v=1777873501770",
      "isVideo": false
    },
    {
      "name": "5.png",
      "type": "Image",
      "size": "1.7 MB",
      "date": "May 3, 2026",
      "src": "TOMIN%20INDEX.TXT/Nume%CC%81ro%20Berlin/5.png?v=1777837540870",
      "isVideo": false
    },
    {
      "name": "6.png",
      "type": "Image",
      "size": "1.8 MB",
      "date": "May 3, 2026",
      "src": "TOMIN%20INDEX.TXT/Nume%CC%81ro%20Berlin/6.png?v=1777837798340",
      "isVideo": false
    },
    {
      "name": "7.png",
      "type": "Image",
      "size": "1004.4 KB",
      "date": "May 3, 2026",
      "src": "TOMIN%20INDEX.TXT/Nume%CC%81ro%20Berlin/7.png?v=1777837540870",
      "isVideo": false
    },
    {
      "name": "9.png",
      "type": "Image",
      "size": "1.7 MB",
      "date": "May 3, 2026",
      "src": "TOMIN%20INDEX.TXT/Nume%CC%81ro%20Berlin/9.png?v=1777838810520",
      "isVideo": false
    },
    {
      "name": "10.png",
      "type": "Image",
      "size": "2.2 MB",
      "date": "May 3, 2026",
      "src": "TOMIN%20INDEX.TXT/Nume%CC%81ro%20Berlin/10.png?v=1777838818860",
      "isVideo": false
    },
    {
      "name": "11.png",
      "type": "Image",
      "size": "47.3 KB",
      "date": "May 3, 2026",
      "src": "TOMIN%20INDEX.TXT/Nume%CC%81ro%20Berlin/11.png?v=1777837540860",
      "isVideo": false
    },
    {
      "name": "12.png",
      "type": "Image",
      "size": "1.4 MB",
      "date": "May 3, 2026",
      "src": "TOMIN%20INDEX.TXT/Nume%CC%81ro%20Berlin/12.png?v=1777837540860",
      "isVideo": false
    },
    {
      "name": "13.png",
      "type": "Image",
      "size": "1.9 MB",
      "date": "May 3, 2026",
      "src": "TOMIN%20INDEX.TXT/Nume%CC%81ro%20Berlin/13.png?v=1777837540860",
      "isVideo": false
    },
    {
      "name": "14.png",
      "type": "Image",
      "size": "1.8 MB",
      "date": "May 3, 2026",
      "src": "TOMIN%20INDEX.TXT/Nume%CC%81ro%20Berlin/14.png?v=1777837540860",
      "isVideo": false
    },
    {
      "name": "15.png",
      "type": "Image",
      "size": "1.7 MB",
      "date": "May 4, 2026",
      "src": "TOMIN%20INDEX.TXT/Nume%CC%81ro%20Berlin/15.png?v=1777878996000",
      "isVideo": false
    },
    {
      "name": "16.png",
      "type": "Image",
      "size": "932.5 KB",
      "date": "May 4, 2026",
      "src": "TOMIN%20INDEX.TXT/Nume%CC%81ro%20Berlin/16.png?v=1777849231260",
      "isVideo": false
    },
    {
      "name": "17.png",
      "type": "Image",
      "size": "806.6 KB",
      "date": "May 3, 2026",
      "src": "TOMIN%20INDEX.TXT/Nume%CC%81ro%20Berlin/17.png?v=1777841093490",
      "isVideo": false
    },
    {
      "name": "19.png",
      "type": "Image",
      "size": "1.2 MB",
      "date": "May 3, 2026",
      "src": "TOMIN%20INDEX.TXT/Nume%CC%81ro%20Berlin/19.png?v=1777837540860",
      "isVideo": false
    },
    {
      "name": "20.png",
      "type": "Image",
      "size": "1.1 MB",
      "date": "May 3, 2026",
      "src": "TOMIN%20INDEX.TXT/Nume%CC%81ro%20Berlin/20.png?v=1777837540860",
      "isVideo": false
    },
    {
      "name": "21.png",
      "type": "Image",
      "size": "2.1 MB",
      "date": "May 3, 2026",
      "src": "TOMIN%20INDEX.TXT/Nume%CC%81ro%20Berlin/21.png?v=1777837540860",
      "isVideo": false
    },
    {
      "name": "22.png",
      "type": "Image",
      "size": "2.1 MB",
      "date": "May 3, 2026",
      "src": "TOMIN%20INDEX.TXT/Nume%CC%81ro%20Berlin/22.png?v=1777837540870",
      "isVideo": false
    },
    {
      "name": "23.png",
      "type": "Image",
      "size": "291.9 KB",
      "date": "May 3, 2026",
      "src": "TOMIN%20INDEX.TXT/Nume%CC%81ro%20Berlin/23.png?v=1777838631610",
      "isVideo": false
    }
  ],
  "TOMIN INDEX.TXT/RUSSH": [
    {
      "name": "1.jpg",
      "type": "Image",
      "size": "1.2 MB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/RUSSH/1.jpg?v=1774706379100",
      "isVideo": false
    },
    {
      "name": "2.jpg",
      "type": "Image",
      "size": "1010.7 KB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/RUSSH/2.jpg?v=1774706379080",
      "isVideo": false
    },
    {
      "name": "3.jpg",
      "type": "Image",
      "size": "960.2 KB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/RUSSH/3.jpg?v=1774706379090",
      "isVideo": false
    },
    {
      "name": "4.jpg",
      "type": "Image",
      "size": "1.5 MB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/RUSSH/4.jpg?v=1774706379100",
      "isVideo": false
    },
    {
      "name": "5.jpg",
      "type": "Image",
      "size": "692 KB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/RUSSH/5.jpg?v=1774706379110",
      "isVideo": false
    },
    {
      "name": "6.jpg",
      "type": "Image",
      "size": "1.2 MB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/RUSSH/6.jpg?v=1774706379100",
      "isVideo": false
    },
    {
      "name": "7.jpg",
      "type": "Image",
      "size": "664.2 KB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/RUSSH/7.jpg?v=1774706379100",
      "isVideo": false
    },
    {
      "name": "8.jpg",
      "type": "Image",
      "size": "365.1 KB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/RUSSH/8.jpg?v=1774706379090",
      "isVideo": false
    },
    {
      "name": "9.jpg",
      "type": "Image",
      "size": "652.5 KB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/RUSSH/9.jpg?v=1774706379090",
      "isVideo": false
    },
    {
      "name": "10.jpg",
      "type": "Image",
      "size": "1019.4 KB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/RUSSH/10.jpg?v=1774706379080",
      "isVideo": false
    },
    {
      "name": "11.jpg",
      "type": "Image",
      "size": "510.7 KB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/RUSSH/11.jpg?v=1774706379080",
      "isVideo": false
    }
  ],
  "bents n glitches": [
    {
      "name": "bent footage edit test HQ.mp4",
      "type": "Video",
      "size": "104.1 MB",
      "date": "Mar 4, 2026",
      "src": "bents%20n%20glitches/bent%20footage%20edit%20test%20HQ_web.mp4?v=1774990399010",
      "isVideo": true
    }
  ],
  "birthday kisses": [
    {
      "name": "birthDayKisses.mp4",
      "type": "Video",
      "size": "192.2 MB",
      "date": "Jun 29, 2024",
      "src": "birthday%20kisses/birthDayKisses_web.mp4?v=1774948418660",
      "isVideo": true
    }
  ],
  "debut": [
    {
      "name": "debut.mp4",
      "type": "Video",
      "size": "809.6 MB",
      "date": "May 27, 2026",
      "src": "debut/debut_web.mp4?v=1780313825370",
      "isVideo": true
    },
    {
      "name": "IMG_004216.mov",
      "type": "QuickTime Movie",
      "size": "11.3 MB",
      "date": "May 22, 2026",
      "src": "debut/IMG_004216.mov?v=1779459331000",
      "isVideo": true
    },
    {
      "name": "IMG_004222.mov",
      "type": "QuickTime Movie",
      "size": "8.1 MB",
      "date": "May 22, 2026",
      "src": "debut/IMG_004222.mov?v=1779463052000",
      "isVideo": true
    }
  ],
  "ftlotg": [
    {
      "name": "ftlotg.mp4",
      "type": "Video",
      "size": "220.3 MB",
      "date": "Jan 14, 2026",
      "src": "ftlotg/ftlotg_web.mp4?v=1774990541240",
      "isVideo": true
    },
    {
      "name": "MOV250919-232418-000281F.mp4",
      "type": "Video",
      "size": "5.3 MB",
      "date": "Jan 14, 2026",
      "src": "ftlotg/MOV250919-232418-000281F.mp4?v=1768408333600",
      "isVideo": true
    }
  ],
  "hlfatpch": [
    {
      "name": "how life feels after the paycheck hits HQ.mp4",
      "type": "Video",
      "size": "95.5 MB",
      "date": "Mar 4, 2026",
      "src": "hlfatpch/how%20life%20feels%20after%20the%20paycheck%20hits%20HQ_web.mp4?v=1774990399280",
      "isVideo": true
    },
    {
      "name": "how mf start movin after getting their moms car keys HQ.mp4",
      "type": "Video",
      "size": "92.1 MB",
      "date": "Mar 6, 2026",
      "src": "hlfatpch/how%20mf%20start%20movin%20after%20getting%20their%20moms%20car%20keys%20HQ_web.mp4?v=1774990399440",
      "isVideo": true
    },
    {
      "name": "late night sketches.mp4",
      "type": "Video",
      "size": "176 MB",
      "date": "Mar 6, 2026",
      "src": "hlfatpch/late%20night%20sketches_web.mp4?v=1774946382260",
      "isVideo": true
    }
  ],
  "lindsay lohan": [
    {
      "name": "lindsay lohan.mp4",
      "type": "Video",
      "size": "34.3 MB",
      "date": "Jul 6, 2025",
      "src": "lindsay%20lohan/lindsay%20lohan_web.mp4?v=1774990399110",
      "isVideo": true
    }
  ],
  "milano": [
    {
      "name": "milano export.mp4",
      "type": "Video",
      "size": "27.2 MB",
      "date": "Jan 13, 2026",
      "src": "milano/milano%20export_web.mp4?v=1774948409140",
      "isVideo": true
    }
  ],
  "schimmel in schladming": [
    {
      "name": "schimmel in schladming HQ.mp4",
      "type": "Video",
      "size": "188.1 MB",
      "date": "Mar 6, 2026",
      "src": "schimmel%20in%20schladming/schimmel%20in%20schladming%20HQ_web.mp4?v=1774990726790",
      "isVideo": true
    }
  ],
  "stoical": [
    {
      "name": "new ideas 120fps.mp4",
      "type": "Video",
      "size": "98.8 MB",
      "date": "Dec 21, 2024",
      "src": "stoical/new%20ideas%20120fps_web.mp4?v=1774990553620",
      "isVideo": true
    },
    {
      "name": "20260114-Screenshot 2026-01-14 at 14.25.12.png",
      "type": "Image",
      "size": "2.8 MB",
      "date": "Jan 14, 2026",
      "src": "stoical/20260114-Screenshot%202026-01-14%20at%2014.25.12.png?v=1768397176020",
      "isVideo": false
    },
    {
      "name": "20260114-Screenshot 2026-01-14 at 14.25.33.png",
      "type": "Image",
      "size": "3.4 MB",
      "date": "Jan 14, 2026",
      "src": "stoical/20260114-Screenshot%202026-01-14%20at%2014.25.33.png?v=1768397175880",
      "isVideo": false
    },
    {
      "name": "20260114-Screenshot 2026-01-14 at 14.25.39.png",
      "type": "Image",
      "size": "3.3 MB",
      "date": "Jan 14, 2026",
      "src": "stoical/20260114-Screenshot%202026-01-14%20at%2014.25.39.png?v=1768397175870",
      "isVideo": false
    },
    {
      "name": "20260114-Screenshot 2026-01-14 at 14.25.49.png",
      "type": "Image",
      "size": "1.9 MB",
      "date": "Jan 14, 2026",
      "src": "stoical/20260114-Screenshot%202026-01-14%20at%2014.25.49.png?v=1768397175830",
      "isVideo": false
    }
  ],
  "tipsy triad": [
    {
      "name": "tipsy triad.mp4",
      "type": "Video",
      "size": "77.6 MB",
      "date": "Mar 5, 2025",
      "src": "tipsy%20triad/tipsy%20triad_web.mp4?v=1774946276570",
      "isVideo": true
    },
    {
      "name": "4-up on 03.03.25 at 20.57 (compiled).jpg",
      "type": "Image",
      "size": "223.3 KB",
      "date": "Mar 4, 2025",
      "src": "tipsy%20triad/4-up%20on%2003.03.25%20at%2020.57%20(compiled).jpg?v=1741114754000",
      "isVideo": false
    },
    {
      "name": "Movie on 03.03.25 at 20.56-0001.png",
      "type": "Image",
      "size": "672.8 KB",
      "date": "Jan 14, 2026",
      "src": "tipsy%20triad/Movie%20on%2003.03.25%20at%2020.56-0001.png?v=1768352739500",
      "isVideo": false
    },
    {
      "name": "Movie on 03.03.25 at 20.58-0001.png",
      "type": "Image",
      "size": "698.7 KB",
      "date": "Jan 14, 2026",
      "src": "tipsy%20triad/Movie%20on%2003.03.25%20at%2020.58-0001.png?v=1768352823490",
      "isVideo": false
    },
    {
      "name": "Movie on 03.03.25 at 21.18-0001.png",
      "type": "Image",
      "size": "1 MB",
      "date": "Jan 14, 2026",
      "src": "tipsy%20triad/Movie%20on%2003.03.25%20at%2021.18-0001.png?v=1768352928120",
      "isVideo": false
    }
  ],
  "valueME": [
    {
      "name": "valueME.mp4",
      "type": "Video",
      "size": "34.2 MB",
      "date": "May 12, 2026",
      "src": "valueME/valueME.mp4?v=1778579588900",
      "isVideo": true
    },
    {
      "name": "IMG_004195.JPG",
      "type": "Image",
      "size": "1.7 MB",
      "date": "May 12, 2026",
      "src": "valueME/IMG_004195.JPG?v=1778588137290",
      "isVideo": false
    },
    {
      "name": "IMG_004204.JPG",
      "type": "Image",
      "size": "1.6 MB",
      "date": "May 9, 2026",
      "src": "valueME/IMG_004204.JPG?v=1778359920000",
      "isVideo": false
    }
  ]
};
export const globalLatestFileTime = 1779832800000;