// Auto-generated by sync.js
// DO NOT EDIT THIS FILE MANUALLY
const portfolioData = {
  "5am in munic": [
    {
      "name": "5am in munich mid quality_web.mp4",
      "type": "Video",
      "size": "84.4 MB",
      "date": "Apr 1, 2026",
      "src": "5am%20in%20munic/5am%20in%20munich%20mid%20quality_web.mp4",
      "isVideo": true
    },
    {
      "name": "5am in munich mid quality.mp4",
      "type": "Video",
      "size": "915 MB",
      "date": "Jan 13, 2026",
      "src": "5am%20in%20munic/5am%20in%20munich%20mid%20quality.mp4",
      "isVideo": true
    },
    {
      "name": "20250921-_DSC4935.jpg",
      "type": "Image",
      "size": "2.2 MB",
      "date": "Jan 14, 2026",
      "src": "5am%20in%20munic/20250921-_DSC4935.jpg",
      "isVideo": false
    },
    {
      "name": "20250923-_DSC4997.jpg",
      "type": "Image",
      "size": "1.5 MB",
      "date": "Jan 14, 2026",
      "src": "5am%20in%20munic/20250923-_DSC4997.jpg",
      "isVideo": false
    },
    {
      "name": "20250923-_DSC4998.jpg",
      "type": "Image",
      "size": "2 MB",
      "date": "Jan 14, 2026",
      "src": "5am%20in%20munic/20250923-_DSC4998.jpg",
      "isVideo": false
    },
    {
      "name": "20250924-_DSC5008.jpg",
      "type": "Image",
      "size": "1.3 MB",
      "date": "Jan 14, 2026",
      "src": "5am%20in%20munic/20250924-_DSC5008.jpg",
      "isVideo": false
    }
  ],
  "LDN x UKG": [
    {
      "name": "london x ukg_compressed.mp4",
      "type": "Video",
      "size": "38.6 MB",
      "date": "Mar 31, 2026",
      "src": "LDN%20x%20UKG/london%20x%20ukg_compressed.mp4",
      "isVideo": true
    },
    {
      "name": "london x ukg_web.mp4",
      "type": "Video",
      "size": "43.6 MB",
      "date": "Mar 31, 2026",
      "src": "LDN%20x%20UKG/london%20x%20ukg_web.mp4",
      "isVideo": true
    },
    {
      "name": "london x ukg.mp4",
      "type": "Video",
      "size": "232.9 MB",
      "date": "Jan 11, 2026",
      "src": "LDN%20x%20UKG/london%20x%20ukg.mp4",
      "isVideo": true
    },
    {
      "name": "20251220-_DSC5252.jpg",
      "type": "Image",
      "size": "2 MB",
      "date": "Jan 14, 2026",
      "src": "LDN%20x%20UKG/20251220-_DSC5252.jpg",
      "isVideo": false
    },
    {
      "name": "20251222-_DSC5308.jpg",
      "type": "Image",
      "size": "1.6 MB",
      "date": "Jan 14, 2026",
      "src": "LDN%20x%20UKG/20251222-_DSC5308.jpg",
      "isVideo": false
    },
    {
      "name": "20251222-_DSC5309.jpg",
      "type": "Image",
      "size": "1.7 MB",
      "date": "Jan 14, 2026",
      "src": "LDN%20x%20UKG/20251222-_DSC5309.jpg",
      "isVideo": false
    },
    {
      "name": "20251222-_DSC5313.jpg",
      "type": "Image",
      "size": "1.8 MB",
      "date": "Jan 14, 2026",
      "src": "LDN%20x%20UKG/20251222-_DSC5313.jpg",
      "isVideo": false
    },
    {
      "name": "20251222-_DSC5325.jpg",
      "type": "Image",
      "size": "1.7 MB",
      "date": "Jan 14, 2026",
      "src": "LDN%20x%20UKG/20251222-_DSC5325.jpg",
      "isVideo": false
    },
    {
      "name": "20251222-_DSC5329.jpg",
      "type": "Image",
      "size": "1.8 MB",
      "date": "Jan 14, 2026",
      "src": "LDN%20x%20UKG/20251222-_DSC5329.jpg",
      "isVideo": false
    },
    {
      "name": "20251222-_DSC5334.jpg",
      "type": "Image",
      "size": "1.9 MB",
      "date": "Jan 14, 2026",
      "src": "LDN%20x%20UKG/20251222-_DSC5334.jpg",
      "isVideo": false
    }
  ],
  "Lunatic": [
    {
      "name": "lunatic_compressed.mp4",
      "type": "Video",
      "size": "23.7 MB",
      "date": "Mar 31, 2026",
      "src": "Lunatic/lunatic_compressed.mp4",
      "isVideo": true
    },
    {
      "name": "lunatic_web.mp4",
      "type": "Video",
      "size": "23.7 MB",
      "date": "Mar 31, 2026",
      "src": "Lunatic/lunatic_web.mp4",
      "isVideo": true
    },
    {
      "name": "lunatic.mp4",
      "type": "Video",
      "size": "120.8 MB",
      "date": "Feb 18, 2025",
      "src": "Lunatic/lunatic.mp4",
      "isVideo": true
    },
    {
      "name": "20250209-_DSC3184.jpg",
      "type": "Image",
      "size": "1 MB",
      "date": "Jan 14, 2026",
      "src": "Lunatic/20250209-_DSC3184.jpg",
      "isVideo": false
    },
    {
      "name": "20250209-_DSC3248.jpg",
      "type": "Image",
      "size": "1005.5 KB",
      "date": "Jan 14, 2026",
      "src": "Lunatic/20250209-_DSC3248.jpg",
      "isVideo": false
    },
    {
      "name": "20250210-_DSC3589.jpg",
      "type": "Image",
      "size": "1.8 MB",
      "date": "Jan 14, 2026",
      "src": "Lunatic/20250210-_DSC3589.jpg",
      "isVideo": false
    },
    {
      "name": "20250214-_DSC4087.jpg",
      "type": "Image",
      "size": "914.6 KB",
      "date": "Jan 14, 2026",
      "src": "Lunatic/20250214-_DSC4087.jpg",
      "isVideo": false
    },
    {
      "name": "20250214-_DSC4114.jpg",
      "type": "Image",
      "size": "1.2 MB",
      "date": "Jan 14, 2026",
      "src": "Lunatic/20250214-_DSC4114.jpg",
      "isVideo": false
    }
  ],
  "TOMIN INDEX.TXT": [
    {
      "name": "032C",
      "type": "Magazine",
      "size": "--",
      "date": "Mar 30, 2026",
      "src": "",
      "isVideo": false,
      "isMagazine": true
    },
    {
      "name": "RUSSH",
      "type": "Magazine",
      "size": "--",
      "date": "Mar 28, 2026",
      "src": "",
      "isVideo": false,
      "isMagazine": true
    }
  ],
  "TOMIN INDEX.TXT/032C": [
    {
      "name": "1.png",
      "type": "Image",
      "size": "1.7 MB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/032C/1.png",
      "isVideo": false
    },
    {
      "name": "2.png",
      "type": "Image",
      "size": "632.6 KB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/032C/2.png",
      "isVideo": false
    },
    {
      "name": "3.png",
      "type": "Image",
      "size": "1.9 MB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/032C/3.png",
      "isVideo": false
    },
    {
      "name": "4.png",
      "type": "Image",
      "size": "2 MB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/032C/4.png",
      "isVideo": false
    },
    {
      "name": "5.png",
      "type": "Image",
      "size": "468.8 KB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/032C/5.png",
      "isVideo": false
    },
    {
      "name": "6.png",
      "type": "Image",
      "size": "887.9 KB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/032C/6.png",
      "isVideo": false
    },
    {
      "name": "7.mp4",
      "type": "Video",
      "size": "375.2 KB",
      "date": "Mar 30, 2026",
      "src": "TOMIN%20INDEX.TXT/032C/7.mp4",
      "isVideo": true
    },
    {
      "name": "7.png",
      "type": "Image",
      "size": "982.3 KB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/032C/7.png",
      "isVideo": false
    },
    {
      "name": "9.png",
      "type": "Image",
      "size": "1.7 MB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/032C/9.png",
      "isVideo": false
    },
    {
      "name": "10.png",
      "type": "Image",
      "size": "1.8 MB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/032C/10.png",
      "isVideo": false
    },
    {
      "name": "11.png",
      "type": "Image",
      "size": "1.1 MB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/032C/11.png",
      "isVideo": false
    },
    {
      "name": "12.png",
      "type": "Image",
      "size": "1.9 MB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/032C/12.png",
      "isVideo": false
    },
    {
      "name": "13.png",
      "type": "Image",
      "size": "2.2 MB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/032C/13.png",
      "isVideo": false
    },
    {
      "name": "14.mp4",
      "type": "Video",
      "size": "455.4 KB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/032C/14.mp4",
      "isVideo": true
    },
    {
      "name": "15.png",
      "type": "Image",
      "size": "777.1 KB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/032C/15.png",
      "isVideo": false
    },
    {
      "name": "16.png",
      "type": "Image",
      "size": "729.4 KB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/032C/16.png",
      "isVideo": false
    },
    {
      "name": "17.png",
      "type": "Image",
      "size": "836.6 KB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/032C/17.png",
      "isVideo": false
    },
    {
      "name": "18.png",
      "type": "Image",
      "size": "771.7 KB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/032C/18.png",
      "isVideo": false
    },
    {
      "name": "19.png",
      "type": "Image",
      "size": "938.5 KB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/032C/19.png",
      "isVideo": false
    },
    {
      "name": "20.png",
      "type": "Image",
      "size": "837.9 KB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/032C/20.png",
      "isVideo": false
    }
  ],
  "TOMIN INDEX.TXT/RUSSH": [
    {
      "name": "1.jpg",
      "type": "Image",
      "size": "1.2 MB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/RUSSH/1.jpg",
      "isVideo": false
    },
    {
      "name": "2.jpg",
      "type": "Image",
      "size": "1010.7 KB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/RUSSH/2.jpg",
      "isVideo": false
    },
    {
      "name": "3.jpg",
      "type": "Image",
      "size": "960.2 KB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/RUSSH/3.jpg",
      "isVideo": false
    },
    {
      "name": "4.jpg",
      "type": "Image",
      "size": "1.5 MB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/RUSSH/4.jpg",
      "isVideo": false
    },
    {
      "name": "5.jpg",
      "type": "Image",
      "size": "692 KB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/RUSSH/5.jpg",
      "isVideo": false
    },
    {
      "name": "6.jpg",
      "type": "Image",
      "size": "1.2 MB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/RUSSH/6.jpg",
      "isVideo": false
    },
    {
      "name": "7.jpg",
      "type": "Image",
      "size": "664.2 KB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/RUSSH/7.jpg",
      "isVideo": false
    },
    {
      "name": "8.jpg",
      "type": "Image",
      "size": "365.1 KB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/RUSSH/8.jpg",
      "isVideo": false
    },
    {
      "name": "9.jpg",
      "type": "Image",
      "size": "652.5 KB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/RUSSH/9.jpg",
      "isVideo": false
    },
    {
      "name": "10.jpg",
      "type": "Image",
      "size": "1019.4 KB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/RUSSH/10.jpg",
      "isVideo": false
    },
    {
      "name": "11.jpg",
      "type": "Image",
      "size": "510.7 KB",
      "date": "Mar 28, 2026",
      "src": "TOMIN%20INDEX.TXT/RUSSH/11.jpg",
      "isVideo": false
    }
  ],
  "bents n glitches": [
    {
      "name": "bent footage edit test HQ_compressed.mp4",
      "type": "Video",
      "size": "21.6 MB",
      "date": "Mar 31, 2026",
      "src": "bents%20n%20glitches/bent%20footage%20edit%20test%20HQ_compressed.mp4",
      "isVideo": true
    },
    {
      "name": "bent footage edit test HQ_web.mp4",
      "type": "Video",
      "size": "21.6 MB",
      "date": "Mar 31, 2026",
      "src": "bents%20n%20glitches/bent%20footage%20edit%20test%20HQ_web.mp4",
      "isVideo": true
    },
    {
      "name": "bent footage edit test HQ.mp4",
      "type": "Video",
      "size": "104.1 MB",
      "date": "Mar 4, 2026",
      "src": "bents%20n%20glitches/bent%20footage%20edit%20test%20HQ.mp4",
      "isVideo": true
    }
  ],
  "birthday kisses": [
    {
      "name": "birthDayKisses_web.mp4",
      "type": "Video",
      "size": "13.3 MB",
      "date": "Mar 31, 2026",
      "src": "birthday%20kisses/birthDayKisses_web.mp4",
      "isVideo": true
    },
    {
      "name": "birthDayKisses.mp4",
      "type": "Video",
      "size": "192.2 MB",
      "date": "Jun 29, 2024",
      "src": "birthday%20kisses/birthDayKisses.mp4",
      "isVideo": true
    }
  ],
  "ftlotg": [
    {
      "name": "ftlotg_compressed.mp4",
      "type": "Video",
      "size": "65.2 MB",
      "date": "Mar 31, 2026",
      "src": "ftlotg/ftlotg_compressed.mp4",
      "isVideo": true
    },
    {
      "name": "ftlotg_web.mp4",
      "type": "Video",
      "size": "28.8 MB",
      "date": "Mar 31, 2026",
      "src": "ftlotg/ftlotg_web.mp4",
      "isVideo": true
    },
    {
      "name": "ftlotg.mp4",
      "type": "Video",
      "size": "220.3 MB",
      "date": "Jan 14, 2026",
      "src": "ftlotg/ftlotg.mp4",
      "isVideo": true
    },
    {
      "name": "MOV250919-232418-000281F.mp4",
      "type": "Video",
      "size": "5.3 MB",
      "date": "Jan 14, 2026",
      "src": "ftlotg/MOV250919-232418-000281F.mp4",
      "isVideo": true
    }
  ],
  "hlfatpch": [
    {
      "name": "how life feels after the paycheck hits HQ_compressed.mp4",
      "type": "Video",
      "size": "62.6 MB",
      "date": "Mar 31, 2026",
      "src": "hlfatpch/how%20life%20feels%20after%20the%20paycheck%20hits%20HQ_compressed.mp4",
      "isVideo": true
    },
    {
      "name": "how life feels after the paycheck hits HQ_web.mp4",
      "type": "Video",
      "size": "62.6 MB",
      "date": "Mar 31, 2026",
      "src": "hlfatpch/how%20life%20feels%20after%20the%20paycheck%20hits%20HQ_web.mp4",
      "isVideo": true
    },
    {
      "name": "how life feels after the paycheck hits HQ.mp4",
      "type": "Video",
      "size": "95.5 MB",
      "date": "Mar 4, 2026",
      "src": "hlfatpch/how%20life%20feels%20after%20the%20paycheck%20hits%20HQ.mp4",
      "isVideo": true
    },
    {
      "name": "how mf start movin after getting their moms car keys HQ_compressed.mp4",
      "type": "Video",
      "size": "45.1 MB",
      "date": "Mar 31, 2026",
      "src": "hlfatpch/how%20mf%20start%20movin%20after%20getting%20their%20moms%20car%20keys%20HQ_compressed.mp4",
      "isVideo": true
    },
    {
      "name": "how mf start movin after getting their moms car keys HQ_web.mp4",
      "type": "Video",
      "size": "45.1 MB",
      "date": "Mar 31, 2026",
      "src": "hlfatpch/how%20mf%20start%20movin%20after%20getting%20their%20moms%20car%20keys%20HQ_web.mp4",
      "isVideo": true
    },
    {
      "name": "how mf start movin after getting their moms car keys HQ.mp4",
      "type": "Video",
      "size": "92.1 MB",
      "date": "Mar 6, 2026",
      "src": "hlfatpch/how%20mf%20start%20movin%20after%20getting%20their%20moms%20car%20keys%20HQ.mp4",
      "isVideo": true
    },
    {
      "name": "late night sketches_compressed.mp4",
      "type": "Video",
      "size": "30.4 MB",
      "date": "Mar 31, 2026",
      "src": "hlfatpch/late%20night%20sketches_compressed.mp4",
      "isVideo": true
    },
    {
      "name": "late night sketches_web.mp4",
      "type": "Video",
      "size": "53.1 MB",
      "date": "Mar 31, 2026",
      "src": "hlfatpch/late%20night%20sketches_web.mp4",
      "isVideo": true
    },
    {
      "name": "late night sketches.mp4",
      "type": "Video",
      "size": "176 MB",
      "date": "Mar 6, 2026",
      "src": "hlfatpch/late%20night%20sketches.mp4",
      "isVideo": true
    }
  ],
  "icons": [
    {
      "name": "bts.png",
      "type": "Image",
      "size": "132.2 KB",
      "date": "Mar 30, 2026",
      "src": "icons/bts.png",
      "isVideo": false
    },
    {
      "name": "contact.png",
      "type": "Image",
      "size": "476.4 KB",
      "date": "Mar 28, 2026",
      "src": "icons/contact.png",
      "isVideo": false
    },
    {
      "name": "edits.png",
      "type": "Image",
      "size": "429.4 KB",
      "date": "Mar 28, 2026",
      "src": "icons/edits.png",
      "isVideo": false
    },
    {
      "name": "finder.png",
      "type": "Image",
      "size": "392.9 KB",
      "date": "Mar 28, 2026",
      "src": "icons/finder.png",
      "isVideo": false
    },
    {
      "name": "flavicon.png",
      "type": "Image",
      "size": "37.5 KB",
      "date": "Mar 30, 2026",
      "src": "icons/flavicon.png",
      "isVideo": false
    },
    {
      "name": "folder.png",
      "type": "Image",
      "size": "54.4 KB",
      "date": "Mar 28, 2026",
      "src": "icons/folder.png",
      "isVideo": false
    },
    {
      "name": "magazine.png",
      "type": "Image",
      "size": "458.1 KB",
      "date": "Mar 28, 2026",
      "src": "icons/magazine.png",
      "isVideo": false
    },
    {
      "name": "mail.png",
      "type": "Image",
      "size": "361.5 KB",
      "date": "Apr 24, 2026",
      "src": "icons/mail.png",
      "isVideo": false
    },
    {
      "name": "profilepicture.png",
      "type": "Image",
      "size": "4.6 MB",
      "date": "Apr 22, 2026",
      "src": "icons/profilepicture.png",
      "isVideo": false
    },
    {
      "name": "tomin-index.png",
      "type": "Image",
      "size": "68.2 KB",
      "date": "Mar 28, 2026",
      "src": "icons/tomin-index.png",
      "isVideo": false
    }
  ],
  "lindsay lohan": [
    {
      "name": "lindsay lohan_compressed.mp4",
      "type": "Video",
      "size": "21.6 MB",
      "date": "Mar 31, 2026",
      "src": "lindsay%20lohan/lindsay%20lohan_compressed.mp4",
      "isVideo": true
    },
    {
      "name": "lindsay lohan_web.mp4",
      "type": "Video",
      "size": "21.6 MB",
      "date": "Mar 31, 2026",
      "src": "lindsay%20lohan/lindsay%20lohan_web.mp4",
      "isVideo": true
    },
    {
      "name": "lindsay lohan.mp4",
      "type": "Video",
      "size": "34.3 MB",
      "date": "Jul 6, 2025",
      "src": "lindsay%20lohan/lindsay%20lohan.mp4",
      "isVideo": true
    }
  ],
  "milano": [
    {
      "name": "milano export_web.mp4",
      "type": "Video",
      "size": "13.8 MB",
      "date": "Mar 31, 2026",
      "src": "milano/milano%20export_web.mp4",
      "isVideo": true
    },
    {
      "name": "milano export.mp4",
      "type": "Video",
      "size": "27.2 MB",
      "date": "Jan 13, 2026",
      "src": "milano/milano%20export.mp4",
      "isVideo": true
    }
  ],
  "schimmel in schladming": [
    {
      "name": "schimmel in schladming HQ_web.mp4",
      "type": "Video",
      "size": "172.4 MB",
      "date": "Mar 31, 2026",
      "src": "schimmel%20in%20schladming/schimmel%20in%20schladming%20HQ_web.mp4",
      "isVideo": true
    },
    {
      "name": "schimmel in schladming HQ.mp4",
      "type": "Video",
      "size": "188.1 MB",
      "date": "Mar 6, 2026",
      "src": "schimmel%20in%20schladming/schimmel%20in%20schladming%20HQ.mp4",
      "isVideo": true
    }
  ],
  "stoical": [
    {
      "name": "new ideas 120fps_web.mp4",
      "type": "Video",
      "size": "30.8 MB",
      "date": "Mar 31, 2026",
      "src": "stoical/new%20ideas%20120fps_web.mp4",
      "isVideo": true
    },
    {
      "name": "new ideas 120fps.mp4",
      "type": "Video",
      "size": "98.8 MB",
      "date": "Dec 21, 2024",
      "src": "stoical/new%20ideas%20120fps.mp4",
      "isVideo": true
    },
    {
      "name": "20260114-Screenshot 2026-01-14 at 14.25.12.png",
      "type": "Image",
      "size": "2.8 MB",
      "date": "Jan 14, 2026",
      "src": "stoical/20260114-Screenshot%202026-01-14%20at%2014.25.12.png",
      "isVideo": false
    },
    {
      "name": "20260114-Screenshot 2026-01-14 at 14.25.33.png",
      "type": "Image",
      "size": "3.4 MB",
      "date": "Jan 14, 2026",
      "src": "stoical/20260114-Screenshot%202026-01-14%20at%2014.25.33.png",
      "isVideo": false
    },
    {
      "name": "20260114-Screenshot 2026-01-14 at 14.25.39.png",
      "type": "Image",
      "size": "3.3 MB",
      "date": "Jan 14, 2026",
      "src": "stoical/20260114-Screenshot%202026-01-14%20at%2014.25.39.png",
      "isVideo": false
    },
    {
      "name": "20260114-Screenshot 2026-01-14 at 14.25.49.png",
      "type": "Image",
      "size": "1.9 MB",
      "date": "Jan 14, 2026",
      "src": "stoical/20260114-Screenshot%202026-01-14%20at%2014.25.49.png",
      "isVideo": false
    }
  ],
  "tipsy triad": [
    {
      "name": "tipsy triad_web.mp4",
      "type": "Video",
      "size": "46.4 MB",
      "date": "Mar 31, 2026",
      "src": "tipsy%20triad/tipsy%20triad_web.mp4",
      "isVideo": true
    },
    {
      "name": "tipsy triad.mp4",
      "type": "Video",
      "size": "77.6 MB",
      "date": "Mar 5, 2025",
      "src": "tipsy%20triad/tipsy%20triad.mp4",
      "isVideo": true
    },
    {
      "name": "4-up on 03.03.25 at 20.57 (compiled).jpg",
      "type": "Image",
      "size": "223.3 KB",
      "date": "Mar 4, 2025",
      "src": "tipsy%20triad/4-up%20on%2003.03.25%20at%2020.57%20(compiled).jpg",
      "isVideo": false
    },
    {
      "name": "Movie on 03.03.25 at 20.56-0001.png",
      "type": "Image",
      "size": "672.8 KB",
      "date": "Jan 14, 2026",
      "src": "tipsy%20triad/Movie%20on%2003.03.25%20at%2020.56-0001.png",
      "isVideo": false
    },
    {
      "name": "Movie on 03.03.25 at 20.58-0001.png",
      "type": "Image",
      "size": "698.7 KB",
      "date": "Jan 14, 2026",
      "src": "tipsy%20triad/Movie%20on%2003.03.25%20at%2020.58-0001.png",
      "isVideo": false
    },
    {
      "name": "Movie on 03.03.25 at 21.18-0001.png",
      "type": "Image",
      "size": "1 MB",
      "date": "Jan 14, 2026",
      "src": "tipsy%20triad/Movie%20on%2003.03.25%20at%2021.18-0001.png",
      "isVideo": false
    }
  ]
};
const globalLatestFileTime = 1776981600000;