/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./app.js",
    "./changelog.js",
    "./admin.js",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#e6e8ec",
        "surface-variant": "#dfe3e7",
        "tertiary": "#c1000a",
        "on-secondary-fixed": "#3e3f43",
        "inverse-primary": "#4b8eff",
        "primary": "#007AFF",
        "on-error": "#fff7f6",
        "surface-container": "#eceef1",
        "on-secondary-container": "#515156",
        "background": "#f9f9fb",
        "error-container": "#fa746f",
        "outline": "#777b7f",
        "error-dim": "#67040d",
        "inverse-on-surface": "#9c9d9f",
        "secondary-container": "#e3e2e7",
        "tertiary-fixed": "#f9362c",
        "surface-dim": "#d7dadf",
        "tertiary-dim": "#ab0008",
        "error": "#a83836",
        "on-primary": "#f9f8ff",
        "on-secondary-fixed-variant": "#5b5b60",
        "on-primary-fixed-variant": "#f8f8ff",
        "secondary": "#5e5f63",
        "surface-container-highest": "#dfe3e7",
        "on-surface": "#2e3336",
        "on-tertiary-fixed-variant": "#150000",
        "primary-fixed-dim": "#006ee6",
        "on-background": "#2e3336",
        "surface": "#f9f9fb",
        "on-surface-variant": "#5b6063",
        "on-error-container": "#6e0a12",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#f9f8fe",
        "surface-container-low": "#f2f4f6",
        "inverse-surface": "#0c0e10",
        "on-tertiary-container": "#000000",
        "outline-variant": "#aeb2b6",
        "on-tertiary": "#fff7f6",
        "primary-fixed": "#007aff",
        "primary-dim": "#0050ab",
        "on-primary-fixed": "#ffffff",
        "surface-bright": "#f9f9fb",
        "tertiary-container": "#f9362c",
        "on-primary-container": "#000000",
        "secondary-fixed": "#e3e2e7",
        "secondary-fixed-dim": "#d5d4d9",
        "tertiary-fixed-dim": "#e62721",
        "secondary-dim": "#525357",
        "primary-container": "#007aff",
        "on-tertiary-fixed": "#000000",
        "surface-tint": "#005bc2",
      },
      fontFamily: {
        headline: ["Inter"],
        body: ["Inter"],
        label: ["Inter"],
      },
      borderRadius: { DEFAULT: "0.5rem", lg: "0.5rem", xl: "0.75rem", full: "9999px" },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
