// ─────────────────────────────────────────────────────────────────────
// Desktop Icons — data-driven renderer
//
// Single source of truth: portfolioData (from data.js, regenerated by
// sync.cjs from the local folders). Every edit project becomes a desktop
// icon automatically. Magazines live inside TOMIN INDEX.TXT and are NOT
// rendered as desktop icons — only the TOMIN INDEX.TXT folder itself is.
//
// Layout model:
//   The desktop is a grid of slots growing from the top-right corner.
//   A slot is identified by { col, row } where col=0 is the rightmost
//   column. Pixel positions are computed from slots; we never store
//   pixels.
//
// Position persistence:
//   localStorage key `desktopIconLayout` holds { "<name>": {col,row} }.
//   - First visit: empty → fall back to DEFAULT_LAYOUT (current hand-
//     curated arrangement).
//   - Drag & drop a icon: layout map is updated and persisted.
//   - New project appears: assigned to the first free slot.
//   - Project removed from data.js: its entry is pruned on next load.
// ─────────────────────────────────────────────────────────────────────

import { portfolioData } from '../../data.js';

const STORAGE_KEY = 'desktopIconLayout';
const COL_STEP = 100;       // px between columns (grows leftward)
const ROW_STEP = 100;       // px between rows (grows downward)
const COL_ORIGIN = 24;      // right offset of col 0
const ROW_ORIGIN = 64;      // top offset of row 0
const SNAP_THRESHOLD = 50;  // px — how close to a slot to snap on drop

// Per-project icon overrides. Anything not listed uses icons/folder.png.
const ICON_OVERRIDES = {
  'TOMIN INDEX.TXT': 'icons/tomin-index.png',
};

// The hand-curated arrangement that was previously baked into index.html.
// Used only on first visit (or when a project has no saved slot yet).
const DEFAULT_LAYOUT = {
  'LDN x UKG':              { col: 0, row: 0 },
  'milano':                 { col: 0, row: 1 },
  'tipsy triad':            { col: 0, row: 2 },
  'birthday kisses':        { col: 0, row: 3 },
  'ftlotg':                 { col: 0, row: 4 },
  '5am in munich':          { col: 0, row: 5 },
  'lindsay lohan':          { col: 1, row: 0 },
  'Lunatic':                { col: 1, row: 1 },
  'hlfatpch':               { col: 1, row: 2 },
  'bents n glitches':       { col: 1, row: 3 },
  'stoical':                { col: 1, row: 4 },
  'schimmel in schladming': { col: 1, row: 5 },
  'TOMIN INDEX.TXT':        { col: 2, row: 0 },
};

// ─────────────────────────────────────────────────────────────────────
// Storage helpers
// ─────────────────────────────────────────────────────────────────────
function loadLayout() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return {};
    const parsed = JSON.parse(raw);
    return (parsed && typeof parsed === 'object') ? parsed : {};
  } catch {
    return {};
  }
}

function saveLayout(layout) {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(layout));
  } catch {
    // localStorage full or disabled — non-fatal, positions just won't persist.
  }
}

// ─────────────────────────────────────────────────────────────────────
// Slot ↔ pixel math
// ─────────────────────────────────────────────────────────────────────
function slotToPx(slot) {
  return {
    right: COL_ORIGIN + slot.col * COL_STEP,
    top: ROW_ORIGIN + slot.row * ROW_STEP,
  };
}

// Convert a free pixel position (during drag) back to the nearest slot.
// Returns null if not close enough to any slot — caller can decide to
// keep the free position or snap.
function pxToNearestSlot(leftPx, topPx, containerWidth, iconWidth) {
  // Convert left → right offset
  const rightPx = containerWidth - leftPx - iconWidth;
  const col = Math.round((rightPx - COL_ORIGIN) / COL_STEP);
  const row = Math.round((topPx - ROW_ORIGIN) / ROW_STEP);
  if (col < 0 || row < 0) return null;
  const exact = slotToPx({ col, row });
  const dx = Math.abs(rightPx - exact.right);
  const dy = Math.abs(topPx - exact.top);
  if (dx > SNAP_THRESHOLD || dy > SNAP_THRESHOLD) return null;
  return { col, row };
}

// ─────────────────────────────────────────────────────────────────────
// Slot assignment for new projects
// ─────────────────────────────────────────────────────────────────────
// Walk the grid column by column, row by row, and return the first slot
// not present in `taken`. We sweep columns outward (0, 1, 2, …) and rows
// downward — same growth direction as the original hand layout.
function firstFreeSlot(taken) {
  const occupied = new Set(taken.map((s) => `${s.col}:${s.row}`));
  for (let col = 0; col < 20; col++) {
    for (let row = 0; row < 20; row++) {
      if (!occupied.has(`${col}:${row}`)) return { col, row };
    }
  }
  return { col: 0, row: 0 }; // pathological fallback
}

// ─────────────────────────────────────────────────────────────────────
// Pick which portfolioData keys deserve a desktop icon
// ─────────────────────────────────────────────────────────────────────
// Rule: top-level folders only. Magazine sub-keys (e.g.
// "TOMIN INDEX.TXT/Issue 1") contain a "/" and are skipped — they're
// accessed *through* the TOMIN INDEX.TXT icon, not as their own icons.
function desktopProjects() {
  return Object.keys(portfolioData).filter((k) => !k.includes('/'));
}

// ─────────────────────────────────────────────────────────────────────
// Resolve final layout: every current project → a slot
// ─────────────────────────────────────────────────────────────────────
// Priority for each project's slot:
//   1. Saved user layout (localStorage)
//   2. DEFAULT_LAYOUT (hand-curated arrangement)
//   3. Next free slot (auto-assigned for brand-new projects)
//
// Also prunes saved entries for projects that no longer exist, so the
// storage doesn't accumulate ghosts.
function resolveLayout(projects) {
  const saved = loadLayout();
  const resolved = {};
  const taken = [];

  // Pass 1: anything with a saved or default slot
  for (const name of projects) {
    const slot = saved[name] || DEFAULT_LAYOUT[name];
    if (slot) {
      resolved[name] = slot;
      taken.push(slot);
    }
  }

  // Pass 2: brand-new projects → first free slot
  for (const name of projects) {
    if (resolved[name]) continue;
    const slot = firstFreeSlot(taken);
    resolved[name] = slot;
    taken.push(slot);
  }

  // Persist the resolved layout so future loads are stable even if
  // DEFAULT_LAYOUT changes or new auto-assignments happen.
  saveLayout(resolved);
  return resolved;
}

// ─────────────────────────────────────────────────────────────────────
// DOM rendering
// ─────────────────────────────────────────────────────────────────────
function iconHTML(name, slot) {
  const { right, top } = slotToPx(slot);
  const iconSrc = ICON_OVERRIDES[name] || 'icons/folder.png';
  // Mirror the markup of the original hand-written icons in index.html
  // so all existing styles, click handlers, and context-menu bindings
  // pick these up unchanged.
  const el = document.createElement('div');
  el.className = 'desktop-icon absolute group flex flex-col items-center space-y-1 cursor-pointer';
  el.style.top = `${top}px`;
  el.style.right = `${right}px`;
  el.dataset.name = name;
  el.innerHTML = `
    <div class="w-[60px] h-[60px] group-hover:scale-110 transition-all duration-200 drop-shadow-lg group-hover:drop-shadow-xl">
      <img src="${iconSrc}" class="w-full h-full object-contain" draggable="false" />
    </div>
    <span class="text-[11px] font-medium text-slate-800 dark:text-white/90 bg-white/50 dark:bg-black/50 px-1.5 py-0.5 rounded-md backdrop-blur-md shadow-sm">${escapeHtml(name)}</span>
  `;
  return el;
}

function escapeHtml(s) {
  return s.replace(/[&<>"']/g, (c) => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
  }[c]));
}

// ─────────────────────────────────────────────────────────────────────
// Drop-snap hook
// ─────────────────────────────────────────────────────────────────────
// The drag logic itself lives in windows.js and operates on free pixel
// coordinates. After a drop we want to (a) snap to the nearest slot if
// close, (b) persist the new slot to localStorage. We do this via a
// mouseup listener on the container that inspects the icon's final
// position and rewrites it if a snap is warranted.
function bindSnapOnDrop(container) {
  let pressed = null;
  let pressStart = null;
  container.addEventListener('mousedown', (e) => {
    const icon = e.target.closest('.desktop-icon');
    pressed = icon || null;
    pressStart = icon ? { x: e.clientX, y: e.clientY } : null;
  });
  document.addEventListener('mouseup', (e) => {
    const icon = pressed;
    const start = pressStart;
    pressed = null;
    pressStart = null;
    if (!icon || !start) return;
    // Skip pure clicks — windows.js rewrites style.left on every mousedown,
    // so without this guard a non-drag click would re-snap (and the rounding
    // walks the icon one slot left each time).
    const moved = Math.abs(e.clientX - start.x) > 3 || Math.abs(e.clientY - start.y) > 3;
    if (!moved) return;
    // Defer one frame so windows.js has finished writing left/top.
    requestAnimationFrame(() => {
      const left = parseFloat(icon.style.left);
      const top = parseFloat(icon.style.top);
      if (Number.isNaN(left) || Number.isNaN(top)) return;
      const containerWidth = container.getBoundingClientRect().width;
      const slot = pxToNearestSlot(left, top, containerWidth, icon.offsetWidth);
      if (!slot) return; // dropped far from any slot — leave it where it is
      const px = slotToPx(slot);
      icon.style.left = 'auto';
      icon.style.top = `${px.top}px`;
      icon.style.right = `${px.right}px`;
      // Persist
      const layout = loadLayout();
      layout[icon.dataset.name] = slot;
      saveLayout(layout);
    });
  });
}

// ─────────────────────────────────────────────────────────────────────
// Main: render all icons into the container
// ─────────────────────────────────────────────────────────────────────
function renderDesktopIcons() {
  const container = document.getElementById('desktop-icons-container');
  if (!container) return;

  const projects = desktopProjects();
  const layout = resolveLayout(projects);

  // Wipe anything that was there (defensive — index.html should ship
  // with an empty container after the migration).
  container.innerHTML = '';

  for (const name of projects) {
    container.appendChild(iconHTML(name, layout[name]));
  }

  bindSnapOnDrop(container);
}

// Render synchronously on module load. app.js imports this BEFORE
// windows.js, so the static querySelectorAll('.desktop-icon') in
// windows.js picks up our freshly-rendered icons and wires up the
// existing drag/click/dblclick handlers.
if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', renderDesktopIcons, { once: true });
} else {
  renderDesktopIcons();
}
